README.md
Add title and description of awesome VTK list.
=> Add title and description of awesome VTK list

README.md
=> Add Applications section

README.md
Add Higher-level interfaces in Python section.
=> Add Higher-level interfaces in Python section

README.md
Add Official section to curated list of VTK.
=> Add Official section to curated list of VTK

README.md
Add Books section as a curated list of VTK.
=> Add Books section as a curated list of VTK

.github/PULL_REQUEST_TEMPLATE.md, README.md
Mayavi: 3D visualization of scientific data in Python
Mayavi seeks to provide easy and interactive visualization of 3D data. It does
this by the following:
- an (optional) rich user interface with dialogs to interact with all data
and objects in the visualization.
- a simple and clean scripting interface in Python, including one-liners,
a-la mlab, or object-oriented programming interface.
- harnesses the power of the VTK toolkit without forcing you to learn it.
--
=> Add Mayavi

README.md
=> Add logo of vtk

CONTRIBUTING.md
=> Setting guidelines for repository contributors

README.md
VTK.js is a complete rewrite of VTK/C++ using plain JavaScript (ES6). So far, the rewrite's focus has been the rendering pipeline for ImageData and PolyData, the pipeline infrastructure, and frequently used readers (obj, stl, vtp, vti). Some filters are also provided as demonstrations. We are not aiming for vtk.js to provide the same set of filters that is available in VTK/C++, but vtk.js does provide the infrastructure needed to define pipelines and filters.
vtk.js aims to be a subset of VTK and provide 3D rendering using WebGL (+WebGPU) for geometry and volume rendering.
--
=> Add vtk-js

README.md
This application can be used in earth sciences like natural resources estimation and other application of geomodeling algorithms such as kriging, sequential Gaussian simulation, sequential indicator simulation, Markov chains random fields, Wavelet transform, etc..
This is an open source and freeware alternative to WinGSLib mainly targeted at post-grad students and industrial users.
--
=> Adding the VTK-powered application GammaRay.

README.md
🕸️ input/output for many mesh formats
--
=> Add meshio

README.md
=> Fix a typo in F3D name

README.md
=> Sort list and use GitHub topics as section

README.md
BVTKNodes is a Blender add-on that wraps the Visualization Toolkit (VTK) library for scientific visualization in Blender. The high-level features of this add-on include:
- Node system for developing VTK pipelines
- Converters from VTK data to Blender meshes, particles and volumes
- Common scientific color maps
BVTKNodes can be used with Blender's powerful 3D modeling and rendering tools to make figures that are both informative as well as visually stunning. This fork builds on the [original repository](https://github.com/simboden/BVtkNodes). Aim is to provide continued updates to newer Blender/VTK versions, new features, bug fixes and community involvement.
<p  align="center">
</p>
--
=> Add BVTKNodes

README.md
Bringing vtk.js into Dash and Python.
--
=> Add Dash VTK

README.md
ITK-Wasm
https://wasm.itk.org/en/latest/
**License:**
[Apache-2.0 license](https://github.com/InsightSoftwareConsortium/itk-wasm#Apache-2.0-1-ov-file)
New Software Project
=> Add ITK-Wasm

README.md
=> Move logo from left to center

README.md
Reverts tkoyama010/awesome-vtk#43
=> Revert "Move logo from left to center"

README.md
=> Add awesome-pyvista

README.md
=> Add awesome-scientific-visualization

.pre-commit-config.yaml, README.md, sort_markdown_list.py
=> Add sort markdown list pre-commit hook to sort items

.pre-commit-config.yaml, ruff.toml, sort_markdown_list.py
=> Add ruff to pre-commit hook to format python script

README.md
=> Add awesome-finite-elements

README.md
=> Add Wikipedia

README.md
=> Add Discourse

README.md
**Project name:** vtkbool
**Project website/repository:** https://github.com/zippy84/vtkbool
**License:** [Apache-2.0 license](https://github.com/zippy84/vtkbool?tab=readme-ov-file#Apache-2.0-1-ov-file)
**Submission type:** New Software Project
=> Add vtkbool

README.md
=> Add link to VTK logo

README.md
**Project name:** SpinView
**Project website/repository:** https://github.com/MXJK851/SpinView
**License:** [GPL-3.0 license](https://github.com/MXJK851/SpinView#GPL-3.0-1-ov-file)
New Software Project
=> Add SpinView

.pre-commit-config.yaml, ruff.toml
=> `toml` ファイルを整形・ソートする `taplo` pre-commit hookを追加

.pre-commit-config.yaml
=> Add zizmor security linter to pre-commit

README.md
=> docs: add Code of Conduct badge to README
